// Pages and Components
export const SET_WHICH_CORE_COMPONENTS_DISPLAY = "SET_WHICH_CORE_COMPONENTS_DISPLAY";
export const SET_WHICH_ACCOUNT_COMPONENTS_DISPLAY = "SET_WHICH_ACCOUNT_COMPONENTS_DISPLAY";
export const SET_WHICH_PROJECT_COMPONENTS_DISPLAY = "SET_WHICH_PROJECT_COMPONENTS_DISPLAY";
// Display Size
export const SET_DISPLAY_SIZE_CONSTANTS = "SET_DISPLAY_SIZE_CONSTANTS";
export const SET_DISPLAY_SIZE_VARIABLES = "SET_DISPLAY_SIZE_VARIABLES";
// priority-status options
export const SET_PRIORITY_STATUS_ARRAYS = "SET_PRIORITY_STATUS_ARRAYS";
// Accounts
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_ACCOUNT = "SET_ACCOUNT";
// Projects
export const SET_PROJECTS = "SET_PROJECTS";
// searchSortFilter
export const SET_PROJECTS_SEARCH_FILTER_SORT = "SET_PROJECTS_SEARCH_FILTER_SORT";
// Mass delete
export const SET_MASS_DELETE_LIST = "SET_MASS_DELETE_LIST";
// Errors
export const SET_INPUT_ERRORS = "SET_INPUT_ERRORS";
