// Pages and Components
export const SET_WHICH_AUTH_COMPONENTS_DISPLAY = "SET_WHICH_AUTH_COMPONENTS_DISPLAY";
export const SET_WHICH_ACCOUNT_COMPONENTS_DISPLAY = "SET_WHICH_ACCOUNT_COMPONENTS_DISPLAY";
export const SET_WHICH_PROJECT_COMPONENTS_DISPLAY = "SET_WHICH_PROJECT_COMPONENTS_DISPLAY";
// priority-status options
export const SET_PRIORITY_STATUS_ARRAYS = "SET_PRIORITY_STATUS_ARRAYS";
// Accounts
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_ACCOUNT = "SET_ACCOUNT";
// Projects
export const SET_PROJECTS = "SET_PROJECTS";
// Errors
export const SET_INPUT_ERRORS = "SET_INPUT_ERRORS";
