export const GENERAL_CONTAINER = "GENERAL_CONTAINER";
export const SIZE_CONTAINER = "SIZE_CONTAINER";
export const ACCOUNT_CONTAINER = "ACCOUNT_CONTAINER";
export const PROJECT_CONTAINER = "PROJECT_CONTAINER";