export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_INPUT_ERRORS = "SET_INPUT_ERRORS";
export const SET_MODAL_COMPONENT = "SET_MODAL_COMPONENT";