// Components
export const SET_WHICH_GENERAL_COMPONENTS_DISPLAY = "SET_WHICH_GENERAL_COMPONENTS_DISPLAY";
export const SET_WHICH_GENERAL_DROPDOWNS_DISPLAY = "SET_WHICH_GENERAL_DROPDOWNS_DISPLAY";
export const SET_WHICH_ACCOUNT_COMPONENTS_DISPLAY = "SET_WHICH_ACCOUNT_COMPONENTS_DISPLAY";
export const SET_WHICH_LIST_AND_ITEM_COMPONENTS_DISPLAY = "SET_WHICH_LIST_AND_ITEM_COMPONENTS_DISPLAY";
export const SET_WHICH_COMMENT_COMPONENTS_DISPLAY = "SET_WHICH_COMMENT_COMPONENTS_DISPLAY";
// Display size
export const SET_DISPLAY_SIZE_CONSTANTS = "SET_DISPLAY_SIZE_CONSTANTS";
export const SET_DISPLAY_SIZE_VARIABLES_WINDOW_AND_MENUS = "SET_DISPLAY_SIZE_VARIABLES_WINDOW_AND_MENUS";
// Reference data
export const SET_THEMES = "SET_THEMES";
export const SET_SORT_CATEGORIES = "SET_SORT_CATEGORIES";
export const SET_PRIORITY_STATUS = "SET_PRIORITY_STATUS";
// Accounts
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_ACCOUNT_SETTINGS = "SET_ACCOUNT_SETTINGS";
// List of projects & list of bugs
export const SET_LIST = "SET_LIST";
// Comments
export const SET_COMMENTS = "SET_COMMENTS";
// searchSortFilter
export const SET_SEARCH_FILTER_SORT = "SET_SEARCH_FILTER_SORT";
// Mass delete
export const SET_MASS_DELETE_LIST = "SET_MASS_DELETE_LIST";
// Errors
export const SET_ERROR_MESSAGES = "SET_ERROR_MESSAGES";
// Should be used in all container reducers for resetting to their initial state
export const RESET_CONTAINER = "RESET_CONTAINER";
