// Components
export const SET_WHICH_GENERAL_COMPONENTS_DISPLAY = "SET_WHICH_GENERAL_COMPONENTS_DISPLAY";
export const SET_WHICH_ACCOUNT_COMPONENTS_DISPLAY = "SET_WHICH_ACCOUNT_COMPONENTS_DISPLAY";
export const SET_WHICH_LIST_COMPONENTS_DISPLAY = "SET_WHICH_LIST_COMPONENTS_DISPLAY";
export const SET_WHICH_COMMENT_COMPONENTS_DISPLAY = "SET_WHICH_COMMENT_COMPONENTS_DISPLAY";
// Display Size
export const SET_DISPLAY_SIZE_CONSTANTS = "SET_DISPLAY_SIZE_CONSTANTS";
export const SET_DISPLAY_SIZE_VARIABLES_WINDOW_NAVBAR = "SET_DISPLAY_SIZE_VARIABLES_WINDOW_NAVBAR";
export const SET_DISPLAY_SIZE_VARIABLES_BREADCRUMB_FONT_SIZE = "SET_DISPLAY_SIZE_VARIABLES_BREADCRUMB_FONT_SIZE";
// priority-status options
export const SET_PRIORITY_STATUS = "SET_PRIORITY_STATUS";
// Accounts
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_ACCOUNT = "SET_ACCOUNT";
// Projects/Bugs list
export const SET_LIST = "SET_LIST";
// Comments
export const SET_COMMENTS = "SET_COMMENTS";
// searchSortFilter
export const SET_SEARCH_FILTER_SORT = "SET_SEARCH_FILTER_SORT";
// Mass delete
export const SET_MASS_DELETE_LIST = "SET_MASS_DELETE_LIST";
// Errors
export const SET_BACKEND_ERRORS = "SET_BACKEND_ERRORS";
// Reset Redux
export const RESET_CONTAINER = "RESET_CONTAINER";
